#pragma once

#include <cstdint>
#include <cstddef>
#include <vector>

namespace backup {

// ============================================================================
// Streaming RC4-compatible Encryptor / Decryptor
// ============================================================================
//
// Implements a simple RC4-compatible stream cipher. The key is used to
// initialize a 256-byte S-box via the Key Scheduling Algorithm (KSA),
// and a keystream is generated by the Pseudo-Random Generation Algorithm
// (PRGA). Data is XORed with the keystream byte by byte.
//
// Encryption and decryption are the same operation (XOR with keystream),
// so encrypt() and decrypt() both call the same internal function.
//
// The S-box state is maintained across multiple encrypt/decrypt calls,
// providing a continuous stream within a single file or entire archive.
// ============================================================================

class StreamEncryptor {
public:
    StreamEncryptor();
    ~StreamEncryptor();

    StreamEncryptor(const StreamEncryptor&) = delete;
    StreamEncryptor& operator=(const StreamEncryptor&) = delete;
    StreamEncryptor(StreamEncryptor&&) noexcept;
    StreamEncryptor& operator=(StreamEncryptor&&) noexcept;

    // Initialize the encryptor with a key and IV.
    // Must be called before any encrypt/decrypt operations.
    // The key and IV are concatenated and used to seed the RC4 state.
    // @param key     Key bytes (typically 32 bytes)
    // @param keySize Key size in bytes
    // @param iv      16-byte initialization vector
    // @param ivSize  Must be 16
    // @return        true on success
    bool init(const uint8_t* key, size_t keySize,
              const uint8_t* iv, size_t ivSize);

    // Encrypt data. XORs plaintext with the RC4 keystream.
    // @param data   Plaintext data
    // @param size   Data size in bytes
    // @return       Ciphertext (same size as input)
    std::vector<uint8_t> encrypt(const uint8_t* data, size_t size);

    // Decrypt data. Identical operation to encrypt (XOR with keystream).
    // @param data   Ciphertext data
    // @param size   Data size in bytes
    // @return       Plaintext (same size as input)
    std::vector<uint8_t> decrypt(const uint8_t* data, size_t size);

    // Check if the encryptor has been successfully initialized
    bool isInitialized() const;

private:
    // RC4 S-box (256-byte permutation)
    uint8_t S_[256];
    uint8_t i_ = 0;  // PRGA index i
    uint8_t j_ = 0;  // PRGA index j
    bool initialized_ = false;

    // Internal process function (same for encrypt and decrypt)
    std::vector<uint8_t> process(const uint8_t* data, size_t size);
};

} // namespace backup
